stages:
  prepare_data:
    cmd: python code/datasets/prepare_data.py --test-size ${data.test_size} --random-state ${data.random_state} --outlier-contamination ${data.outlier_contamination}
    deps:
      - code/datasets/prepare_data.py
      - data/raw/cumulative.csv
    params:
      - data.test_size
      - data.random_state
      - data.outlier_contamination
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  train_model:
    cmd: python code/models/train_model.py --random-state ${model.random_state} --max-iter ${model.max_iter} --regularization-strength ${model.regularization_strength}
    deps:
      - code/models/train_model.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - model.random_state
      - model.max_iter
      - model.regularization_strength
    outs:
      - models/exoplanet_classifier.joblib
    metrics:
      - metrics.json
